/* ORDER */
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL"
export const ADD_PRODUCT_DETAIL = "ADD_PRODUCT_DETAIL"
export const ADD_SPECIFIC_DETAIL = "ADD_SPECIFIC_DETAIL"
export const GET_SPECIFIC_DETAIL = "ADD_SPECIFIC_DETAIL"
export const ADD_TESTRESULT_LASTED = "ADD_TESTRESULT_LASTED"
export const GET_TESTRESULT_LASTED = "GET_TESTRESULT_LASTED"
export const ADD_SPECIFIC_BIO_DETAIL = "ADD_SPECIFIC_BIO_DETAIL"
export const GET_SPECIFIC_BIO_DETAIL = "GET_SPECIFIC_BIO_DETAIL"

